# Generated by Django 6.0 on 2025-12-14 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nepse_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopGainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepse_data.company')),
            ],
            options={
                'ordering': ['-date', 'rank'],
                'unique_together': {('date', 'rank', 'company')},
            },
        ),
        migrations.CreateModel(
            name='TopLosers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rank', models.IntegerField()),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nepse_data.company')),
            ],
            options={
                'ordering': ['-date', 'rank'],
                'unique_together': {('date', 'rank', 'company')},
            },
        ),
    ]
