# Generated by Django 5.2.9 on 2025-12-17 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_market_open', models.BooleanField(default=False)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
                ('total_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_volume', models.BigIntegerField(default=0)),
                ('total_transactions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100, null=True)),
                ('listed_shares', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'indexes': [models.Index(fields=['symbol'], name='scrapers_co_symbol_e69b38_idx'), models.Index(fields=['sector'], name='scrapers_co_sector_ac5020_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('last_traded_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volume', models.BigIntegerField(default=0)),
                ('previous_close', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percentage_change', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('turnover', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_count', models.IntegerField(default=0)),
                ('scrape_date', models.DateField()),
                ('scrape_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_data', to='scrapers.company')),
            ],
            options={
                'indexes': [models.Index(fields=['scrape_date', 'company'], name='scrapers_st_scrape__508f67_idx'), models.Index(fields=['scrape_date', 'percentage_change'], name='scrapers_st_scrape__8cf6b9_idx'), models.Index(fields=['scrape_date', 'turnover'], name='scrapers_st_scrape__dab174_idx')],
                'unique_together': {('company', 'scrape_date', 'scrape_time')},
            },
        ),
    ]
