# Generated by Django 5.2.9 on 2025-12-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['symbol'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='marketstatus',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Market Status'},
        ),
        migrations.AlterModelOptions(
            name='stockdata',
            options={'ordering': ['-scrape_date', '-scrape_time', 'symbol'], 'verbose_name_plural': 'Stock Data'},
        ),
        migrations.RemoveIndex(
            model_name='stockdata',
            name='scrapers_st_scrape__508f67_idx',
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='marketstatus',
            name='market_close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='data_source',
            field=models.CharField(choices=[('live', 'Live Market Data'), ('closing', 'Closing Summary'), ('historical', 'Historical/After-Hours')], default='live', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='is_closing_data',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='market_session',
            field=models.CharField(choices=[('pre_open', 'Pre-Open'), ('regular', 'Regular Trading'), ('post_close', 'Post-Close'), ('after_hours', 'After Hours')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='stockdata',
            name='symbol',
            field=models.CharField(db_index=True, default='TEMP', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='marketstatus',
            name='total_turnover',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='scrape_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='scrape_time',
            field=models.TimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='stockdata',
            unique_together={('company', 'scrape_date', 'scrape_time', 'data_source')},
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['scrape_date', 'symbol'], name='scrapers_st_scrape__32aede_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['symbol', 'scrape_date'], name='scrapers_st_symbol_f5c52e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['scrape_date', 'data_source'], name='scrapers_st_scrape__e2b594_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['company', 'scrape_date'], name='scrapers_st_company_53d525_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['is_closing_data'], name='scrapers_st_is_clos_2f54ba_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['created_at'], name='scrapers_st_created_e3469d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockdata',
            index=models.Index(fields=['scrape_date', 'scrape_time'], name='scrapers_st_scrape__29f65d_idx'),
        ),
    ]
