# Generated by Django 5.2.9 on 2025-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_alter_company_options_alter_marketstatus_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='stockdata',
            name='scrapers_st_scrape__dab174_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockdata',
            name='scrapers_st_company_53d525_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockdata',
            name='scrapers_st_created_e3469d_idx',
        ),
        migrations.RemoveIndex(
            model_name='stockdata',
            name='scrapers_st_scrape__29f65d_idx',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='market_session',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='open_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='transaction_count',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='turnover',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='volume',
        ),
        migrations.AlterField(
            model_name='stockdata',
            name='data_source',
            field=models.CharField(choices=[('live', 'Live Market'), ('closing', 'Closing Summary'), ('historical', 'Historical')], default='live', max_length=20),
        ),
    ]
